---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-labeler
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-labeler
  namespace: default
rules:
# Required for leader election using Lease objects
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update"]
# Required for pod operations
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch"]
  # get: Read pod status for readiness checks
  # list: Discover all participants (leader needs this)
  # patch: Apply labels to pods (leader labels all participants)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-labeler
  namespace: default
subjects:
- kind: ServiceAccount
  name: leader-labeler
  namespace: default
roleRef:
  kind: Role
  name: leader-labeler
  apiGroup: rbac.authorization.k8s.io
